apiVersion: v1
kind: Pod
metadata:
    labels:
        app: eks-builder
    annotations:
        iam.amazonaws.com/role: jenkins
spec:
    containers:
    - name: terragrunt
      image: einyx/terragrunt:0.16
      command:
      - cat
      tty: true
      env:
      - name: AWS_REGION
        value: eu-west-2
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: terratest
            key: access
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: terratest
            key: secret
      resources:
        limits:
          cpu: 500m
          memory: 500Mi